name: Purge obsolete workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '31 2 * * 1'

env:
  SLACK_NOTIFY: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  purge-obsolete-workflows:
    name: Purge obsolete workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Purge obsolete workflow runs
        uses: otto-de/purge-workflow-runs@0de33de0a9fe17321e4cf3c21dcbc0445e7c5b61 # v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - purge-obsolete-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 # v1.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
